# Based on a build template from:
#
# https://docs.haskellstack.org/en/stable/travis_ci/

# Choose a build environment
dist: xenial

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  timeout: 1000

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

jobs:
  include:
    - stage: bigdeps
      name: "Cache some big / time-consuming dependencies"
      addons:
        apt:
          packages:
            - libgmp-dev
      script: stack --no-terminal install diagrams-core JuicyPixels lens
    - stage: build
      name: "Build raindrop library"
      script:
      - stack --no-terminal --install-ghc test --only-dependencies
      - stack --no-terminal test --haddock --no-haddock-deps

stages:
  - bigdeps
  - build
